sudo: required

language: python

python:
  - "2.7"

services:
  - docker
  
before_install:
- docker images
- docker build -t dynamoextractor -f .\Dockerfile .
- docker images
- docker run -d -p 127.0.0.1:5000:5000 dynamoextractor

script:
  - curl 127.0.0.1:5000/secret
  - curl 127.0.0.1:5000/secret | jq '.[].secret_code'

after_success:
   - docker login -u "avnery" -p "5303280"
   - docker push avnery/dynamoextractor:latest
