sudo: required

language: python

python:
  - "2.7"

services:
  - docker
  
before_install:
- docker build -t avnery/dynamoextractor -f .\Dockerfile .
- docker run -d -p 127.0.0.1:5000:5000 avnery/dynamoextractor

script:
  - curl 127.0.0.1:5000/secret
  - curl 127.0.0.1:5000/secret | jq '.[].secret_code'
  - curl 127.0.0.1:5000/health


after_success:
   - docker login -u "avnery" -p "5303280"
   - docker push avnery/dynamoextractor:latest
