sudo: required

language: python

python:
  - "2.7"

services:
  - docker
  
before_install:
- docker build -t dynamoextractor -f .\Dockerfile .
- docker run -d -p 127.0.0.1:5000:5000 dynamoextractor

script:
  - curl 127.0.0.1:5000/secret
  - curl 127.0.0.1:5000/secret | jq '.[].secret_code'

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push avnery/avner-devops:tagname;
    fi
